name: Cancel All Workflows

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type "yes" to confirm cancellation of all workflows'
        required: true
        type: string

jobs:
  cancel:
    runs-on: ubuntu-latest
    if: inputs.confirm == 'yes'
    
    steps:
      - name: Cancel Workflows
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const workflows = [
              'test_parquet_processor.yml',
              'test_parquet_coordinator.yml',
              'test_parquet_aggregator.yml'
            ];
            
            console.log('Fetching running workflow runs...');
            
            for (const workflow of workflows) {
              try {
                const runs = await github.rest.actions.listWorkflowRuns({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  workflow_id: workflow,
                  status: 'in_progress'
                });
                
                console.log(`Found ${runs.data.total_count} running workflows for ${workflow}`);
                
                for (const run of runs.data.workflow_runs) {
                  console.log(`Cancelling workflow run ${run.id} (${workflow})`);
                  
                  try {
                    await github.rest.actions.cancelWorkflowRun({
                      owner: context.repo.owner,
                      repo: context.repo.repo,
                      run_id: run.id
                    });
                    console.log(`Successfully cancelled workflow run ${run.id}`);
                  } catch (cancelError) {
                    console.error(`Error cancelling workflow run ${run.id}:`, cancelError);
                  }
                  
                  // Small delay between cancellations
                  await new Promise(resolve => setTimeout(resolve, 1000));
                }
              } catch (error) {
                console.error(`Error processing workflow ${workflow}:`, error);
              }
            }
            
      - name: Summary
        run: |
          echo "# Workflow Cancellation Summary" > cancellation_summary.md
          echo "All matching workflows have been cancelled." >> cancellation_summary.md
          echo "Please check the logs above for details on specific cancellations." >> cancellation_summary.md
          
      - name: Upload Summary
        uses: actions/upload-artifact@v4
        with:
          name: cancellation-summary
          path: cancellation_summary.md 