name: Lint Workflows

on:
  pull_request:
    paths:
      - '.github/workflows/**'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Check workflow files
        uses: reviewdog/action-actionlint@v1
        with:
          reporter: github-pr-review
          fail_on_error: true 