name: Setup Environment

on:
  workflow_call:
    inputs:
      python-version:
        required: false
        type: string
        default: "3.10"
      install-chrome:
        required: false
        type: boolean
        default: false

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
          
      - name: Create and activate virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Install Chrome and ChromeDriver
        if: inputs.install-chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      # Cache the virtual environment
      - name: Cache virtual environment
        uses: actions/cache@v4
        with:
          path: venv
          key: venv-${{ runner.os }}-${{ inputs.python-version }}-${{ hashFiles('requirements.txt') }}

      # Upload the environment as an artifact for reuse
      - name: Upload virtual environment
        uses: actions/upload-artifact@v4
        with:
          name: venv
          path: venv 