name: Setup Environment

on:
  workflow_call:
    inputs:
      python-version:
        required: false
        type: string
        default: "3.10"
      install-chrome:
        required: false
        type: boolean
        default: false

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
          cache: 'pip'
          
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            
      - name: Install Chrome and ChromeDriver
        if: inputs.install-chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 